# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3378621a8fdfc709c5d900f96d64bb433e6de244e825a28111d295880a389389b939efa7de7ed84788c5882ba6643b84e59990cb391c6dd414907027cfb91b32

test:
  secret_key_base: 91a1acd9d1339ab66a030e40199404db19785ded81ff172f3dc8c32a1e157a4d72336c6b1cced232d37ce33486e939fabb74f1a6a4f6baae9206c705e8b451dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
